name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job para instalar dependências e rodar os testes
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  # Job para rodar o Streamlit e gerar relatórios
  streamlit:
    runs-on: ubuntu-latest
    needs: build_and_test # Espera o primeiro job concluir

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Streamlit app
      run: |
        nohup streamlit run app/your_streamlit_app.py &
        sleep 10  # Dá um tempo para o app carregar

  # Job para gerar embeddings e fazer análise de desempenho
  embeddings:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate Embeddings
      run: |
        python src/embeddings.py  # Executa o script para gerar embeddings
